http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  basic:
    apiEndpoints:
      - api
    policies:
      # - proxy: # see: http://www.express-gateway.io/docs/policies/proxy

